### PR TITLE
Actions added

### PR DESCRIPTION
**Pull request by Insert5StarName**

### CODE REVIEW

**Comment by HackedOS** [comment]
maybe add cargo fmt checks and don't allow merge if it doesn't succeed

**Comment by Insert5StarName** [comment]
better?

**Comment by HackedOS** [comment]
Multiple jobs maybe for better gh interface https://github.com/Smithay/smithay/blob/master/.github/workflows/ci.yml use this as ref maybe

**Review by HackedOS — APPROVED** [review]
This works

**Pull request merged**
